### ISSUE TITLE
Crop recommendation query not found

### ISSUE THREAD

**Issue by Ajuz369** [vineetpatel725/Crop-Recommendation#2]
When I try to deploy the site in local host all otheer pages of websites works really fine . But in the recommendation page when i enter the soil values its showing a traceback error in the site like "crop recommendation query doesn't exist" + some random error

**Comment by vineetpatel725** [comment]
Can you send me a screenshot of the error?

**Comment by Ajuz369** [comment]
> Can you send me a screenshot of the error?
This was actaully found during the recommendation part
![Screenshot (182)](https://user-images.githubusercontent.com/103025064/161933189-e6d2172b-aeec-42be-9722-88eec363f132.png)

![Screenshot (181)](https://user-images.githubusercontent.com/103025064/161933215-feeb45ba-6854-4962-8118-9f7d3d9199b2.png)

**Comment by vineetpatel725** [comment]
It will not work because, it can't find the data from the database. I have updated the repository where you can find out .sql file which you have to import in database. Then, it will work fine.
